/*
This section lists all the active/main members of our team.
We might merge this page into the About Us page.
*/

export default function Members() {
  return;
}

// 'use client'

// import React from "react"
// import Head from 'next/head';
// import { siteConfig } from "@/config/site"
// import { mouseLeave, mouseMove } from "../lib/mouseTracking"
// import Link from "next/link";
// import { useEffect } from 'react';
// import Spline from '@splinetool/react-spline';
// import Image from 'next/image'
// import { cn } from "@/lib/utils"
// import { useTheme } from 'next-themes'
// import { useState } from "react";
// import { grid } from 'ldrs'

// export default function Home() {
//   const [loaded, setLoaded] = useState(false);

//   const delay = ms => new Promise(res => setTimeout(res, ms));
//   useEffect(() => {
//     (
//       async () => {
//         const LocomotiveScroll = (await import('locomotive-scroll')).default
//         const locomotiveScroll = new LocomotiveScroll();
//       }
//     )()
//   }, [])

//   const hideLoader = async () => {
//     await delay(2000);
//     console.log("loading should be complete");
//     window.scrollTo(0,0);
//     setLoaded(true);
//     sessionStorage.setItem('hasLoaded', true);
//   };

//   useEffect(() => {
//     // Check if the flag exists in session storage
//     const hasLoaded = sessionStorage.getItem('hasLoaded');

//     // If the flag is true, hide the loader immediately
//     if (hasLoaded === 'true') {
//       setLoaded(true);
//     } else {
//       // If the flag doesn't exist or is false, show the loader and hide it after delay
//       hideLoader();

//     }
//   }, []);

//   return (
//     <div className="">

//       <div className={`${loaded ? "opacity-0 hidden" : "opacity-100"} fixed inset-0 z-50 transition-all bg-emerald-400 overflow-hidden w-screen h-screen flex justify-center items-center flex-col duration-500`} id="page-loader">
//               <l-grid
//           size="125"
//           speed="1.5"
//           color="white"
//         ></l-grid>
//         <h1 className="text-white font-normal mt-10 text-3xl text-center">
//           Loading...
//         </h1>
//         <h1 className="text-white font-thin mt-5 text-xl text-center">
//           Please use fullscreen for best experience.
//         </h1>
//       </div>

//       <Head>
//         <title>{siteConfig.name}</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//       </Head>

//       <main onMouseMove={mouseMove} onMouseLeave={mouseLeave}>
//         <section className="">
//           <div className="hero h-screen overflow-hidden perspective bg-black">

//             <div className="h-screen min-h-[500px] transform-3d rotate-x-[var(--move-y)] rotate-y-[var(--move-x)] will-change-transform transition-transform ease-out duration-1000">
//               <div className="layer-bg bg-layer-1 -translate-z-[55px] scale-[1.06]" />
//               <div className="layer-bg bg-layer-2 translate-z-20 scale-[.88]" />

//               <div className="layer-content translate-z-[180px] scale-[.8]">
//                 <div className=" mt-[calc(var(--index)*4)] text-[calc(var(--index)*4.35)] text-center uppercase tracking-[calc(var(--index)*-.15)] leading-[.9em]">
//                   <h1 className="text-white text-shadow font-bold">

//                     <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">B</span>
//                     <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">E</span>
//                     <span className=""> </span>
//                     <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">M</span>
//                     <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">I</span>
//                     <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">N</span>
//                     <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">D</span>
//                     <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">F</span>
//                     <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">U</span>
//                     <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">L</span>
//                     <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">.</span>
//                   </h1>

//                   <p className="text-white normal-case tracking-normal text-[calc(var(--index)*.8)] leading-[3] text-shadow">
//                     Have a look around: this could be our future. But how do we get there?
//                   </p>
//                   <p className="text-white normal-case tracking-normal text-[calc(var(--index)*.8)] leading-[.1] text-shadow">

//                   Greenful can help.
//                   </p>
//                 </div>
//               </div>

//               <div className="layer-content translate-z-[190px] scale-[.9] pointer-events-none">
//                 <canvas className="rain" />
//               </div>

//               <div className="layer-bg bg-layer-5 translate-z-[300px] scale-[.9] pointer-events-none" />
//               <div className="layer-bg bg-layer-6 translate-z-[380px] pointer-events-none" />
//             </div>

//             <div className="flex flex-row text-lg absolute bottom-0 left-0 z-[1] mb-10 lg:ml-16 ml-10 items-center text-white">
//               <Link href="/" className="hidden lg:flex">
//                 Scroll to Explore
//               </Link>
//               <Link href="/" className="material-symbols-outlined scale-120 lg:ml-2 pointer-events-auto [color:white]">expand_more</Link>
//             </div>

//           </div>
//         </section>

//         <div  className="sticky top-0 left-0">
//           <section className={cn(
//             "flex justify-center items-center font-semibold h-screen ",
//             "dark:bg-black bg-white",
//             "xl:text-6xl",
//             "lg:text-5xl",
//             "md:text-5xl",
//             "sm:text-5xl",
//             "text-3xl",
//             )}>
//             <Link href="/carbon-footprint-calculator"
//             data-scroll data-scroll-css-progress data-scroll-offset="105%,105%"
//             className={cn(
//               "sm:h-[90vh] sm:w-[95vw] bg-cover bg-background rounded-xl bg-center flex flex-col justify-center",
//               "dark:bg-[url('/front_cards/cc_light.png')]",
//               "bg-[url('/front_cards/cc_dark.png')]",
//               "h-[80vh] w-[95vw]",
//               "opacity-[calc(1-var(--progress))] scale-[calc(1-var(--progress))] blur-[calc( (1-var(--progress)) * 1000 )]")}>
//               <div className={cn(
//                 "xl:mt-[55vh] xl:ml-[6vw]",
//                 "lg:mt-[55vh] lg:ml-[5vw]",
//                 "md:mt-[55vh] md:ml-[5vw]",
//                 "sm:mt-[55vh] sm:ml-[4vw]",
//                 "mt-[55vh] ml-[5vw]"
//               )}>
//                 <h1 className={cn(
//                   "dark:text-black text-white"
//                   )}>
//                   CARBON CALCULATOR
//                 </h1>
//                 <p className={cn(
//                   "font-thin",
//                   "dark:text-black text-white",
//                   "lg:text-3xl lg:mt-5 lg:max-w-4xl",
//                   "md:text-2xl md:mt-4",
//                   "sm:text-2xl sm:mt-3",
//                   "text-xl mt-2 max-w-lg"
//                   )}>
//                   Discover your annual carbon footprint and compare it to the average US household using our calculator.
//                 </p>

//               </div>
//             </Link>
//           </section>
//         </div>

//         <div className="sticky top-0 left-0">
//           <section className={cn(
//             "flex justify-center items-center font-semibold h-screen bg-transparent",
//             "xl:text-6xl",
//             "lg:text-5xl",
//             "md:text-5xl",
//             "sm:text-5xl",
//             "text-3xl")}>
//             <Link href="solutions" data-scroll data-scroll-css-progress data-scroll-offset="105%,105%" className={cn(
//               "sm:h-[90vh] sm:w-[95vw] bg-[length:110%] bg-background rounded-xl bg-center flex flex-col justify-center",
//               "bg-[url('/front_cards/articles.png')]",
//               "h-[80vh] w-[95vw]",
//               "opacity-[calc(1-var(--progress))] scale-[calc(1-var(--progress))] blur-[calc( (1-var(--progress)) * 1000 )]")}>
//               <div className={cn(
//                 "xl:mt-[55vh] xl:ml-[6vw]",
//                 "lg:mt-[55vh] lg:ml-[5vw]",
//                 "md:mt-[55vh] md:ml-[5vw]",
//                 "sm:mt-[55vh] sm:ml-[4vw]",
//                 "mt-[55vh] ml-[5vw]"
//               )}>
//                 <h1 className={cn(
//                   "text-white"
//                   )}>
//                   SOLUTIONS
//                 </h1>
//                 <p className={cn(
//                   "font-thin",
//                   "text-white",
//                   "lg:text-3xl lg:mt-5 lg:max-w-4xl",
//                   "md:text-2xl md:mt-4",
//                   "sm:text-2xl sm:mt-3",
//                   "text-xl mt-2 max-w-lg"
//                   )}>
//                     View some of our hand-picked solutions on how we believe carbon emissions could best be reduced.
//                 </p>

//               </div>
//             </Link>
//           </section>
//         </div>

//         <div className="relative top-0 left-0">
//           <section className={cn(
//             "flex justify-center items-center font-semibold h-screen bg-transparent",
//             "xl:text-6xl",
//             "lg:text-5xl",
//             "md:text-5xl",
//             "sm:text-5xl",
//             "text-3xl",)}
//             >
//             <Link href="/interactive" className={cn(
//               "sm:h-[90vh] sm:w-[95vw] bg-cover bg-background rounded-xl bg-center flex flex-col justify-center",
//               "bg-[url('/front_cards/interactive_house.png')]",
//               "h-[80vh] w-[95vw]")}>
//               <div className={cn(
//                 "xl:mt-[55vh] xl:ml-[6vw]",
//                 "lg:mt-[55vh] lg:ml-[5vw]",
//                 "md:mt-[55vh] md:ml-[5vw]",
//                 "sm:mt-[55vh] sm:ml-[4vw]",
//                 "mt-[55vh] ml-[5vw]"
//               )}>
//                 <h1 className={cn(
//                   "text-white"
//                   )}>
//                   INTERACTIVE HOUSE
//                 </h1>
//                 <p className={cn(
//                   "font-thin",
//                   "text-white",
//                   "lg:text-3xl lg:mt-5 lg:max-w-4xl",
//                   "md:text-2xl md:mt-4",
//                   "sm:text-2xl sm:mt-3",
//                   "text-xl mt-2 max-w-lg"
//                   )}>
//                     Learn different ways to save energy around the house by exploring our virtual house.
//                 </p>

//               </div>
//             </Link>
//           </section>
//         </div>

//         <section className={cn(
//           "h-screen flex justify-center items-center font-semibold bg-black")}>
//               <div className="bg-black mt-[calc(var(--index)*4)] text-[calc(var(--index)*4.35)] text-center uppercase tracking-[calc(var(--index)*-.15)] leading-[.5em] align-center">
//                 <h1 className="dark:text-white text-black dark:text-shadow font-bold">
//                   <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">B</span>
//                   <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">E</span>
//                   <span className=""> </span>
//                   <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">G</span>
//                   <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">R</span>
//                   <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">E</span>
//                   <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">E</span>
//                   <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">N</span>
//                   <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">F</span>
//                   <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">U</span>
//                   <span className="lg:hover:font-stretch font-stretch-zero transition-all ease-out duration-500">L</span>
//                 </h1>

//               </div>

//         </section>

//       </main>
//     </div>
//   );
// }
